//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiImages
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class MultipleMediaRecord
    {
        public int Id { get; set; }
        public string Place { get; set; }
        public string Area { get; set; }
        public string ImagePaths { get; set; }
        public string VideoPaths { get; set; }
        [NotMapped]
        public IEnumerable<HttpPostedFileBase> Images { get; set; } // For image uploads

        [NotMapped]
        public IEnumerable<HttpPostedFileBase> Videos { get; set; }
    }
}
